# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]

[[redirects]]
  from = "/cors-proxy/*"
  to = ":splat"
  status = 200
  force = true